export const FIND_ME_REQUEST = "FIND_ME_REQUEST";
export const FIND_ME_SUCCESS = "FIND_ME_SUCCESS";
export const FIND_ME_FAILURE = "FIND_ME_FAILURE";

export const FIND_USER_BY_USERNAME_REQUEST = "FIND_USER_BY_USERNAME_REQUEST";
export const FIND_USER_BY_USERNAME_SUCCESS = "FIND_USER_BY_USERNAME_SUCCESS";
export const FIND_USER_BY_USERNAME_FAILURE = "FIND_USER_BY_USERNAME_FAILURE";

export const FIND_SUGGESTIONS_REQUEST = "FIND_SUGGESTIONS_REQUEST";
export const FIND_SUGGESTIONS_SUCCESS = "FIND_SUGGESTIONS_SUCCESS";
export const FIND_SUGGESTIONS_FAILURE = "FIND_SUGGESTIONS_FAILURE";
