export const UPDATE_NAME_REQUEST = "UPDATE_NAME_REQUEST";
export const UPDATE_NAME_SUCCESS = "UPDATE_NAME_SUCCESS";
export const UPDATE_NAME_FAILURE = "UPDATE_NAME_FAILURE";

export const UPDATE_EMAIL_REQUEST = "UPDATE_EMAIL_REQUEST";
export const UPDATE_EMAIL_SUCCESS = "UPDATE_EMAIL_SUCCESS";
export const UPDATE_EMAIL_FAILURE = "UPDATE_EMAIL_FAILURE";

export const UPDATE_PASSWORD_REQUEST = "UPDATE_PASSWORD_REQUEST";
export const UPDATE_PASSWORD_SUCCESS = "UPDATE_PASSWORD_SUCCESS";
export const UPDATE_PASSWORD_FAILURE = "UPDATE_PASSWORD_FAILURE";

export const UPDATE_PROFILE_PHOTO_URL_REQUEST =
  "UPDATE_PROFILE_PHOTO_URL_REQUEST";
export const UPDATE_PROFILE_PHOTO_URL_SUCCESS =
  "UPDATE_PROFILE_PHOTO_URL_SUCCESS";
export const UPDATE_PROFILE_PHOTO_URL_FAILURE =
  "UPDATE_PROFILE_PHOTO_URL_FAILURE";

export const TOGGLE_DARK_MODE = "TOGGLE_DARK_MODE";
